export const interactiveHomeSummaryCardClass = [
	"focus-ring",
	"p-4",
	"rounded-[1.35rem]",
	"border",
	"border-app-line/45",
	"bg-app-bg/70",
	"block",
	"transition-[background-color,border-color,box-shadow]",
	"dark:border-app-line-dark/75",
	"dark:bg-app-bg-dark/70",
	"hover:bg-app-bg",
	"hover:border-app-line/80",
	"hover:shadow-[0_18px_40px_rgba(15,23,42,0.08)]",
	"focus-visible:bg-app-bg",
	"focus-visible:border-app-line/80",
	"focus-visible:shadow-[0_18px_40px_rgba(15,23,42,0.08)]",
	"dark:hover:bg-app-panel-dark/95",
	"dark:hover:border-app-line-dark",
	"dark:hover:shadow-[0_18px_40px_rgba(2,8,23,0.42)]",
	"dark:focus-visible:bg-app-panel-dark/95",
	"dark:focus-visible:border-app-line-dark",
	"dark:focus-visible:shadow-[0_18px_40px_rgba(2,8,23,0.42)]",
].join(" ");
